# Generated by Django 5.2.12 on 2026-04-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_cartitem_cart_remove_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('bath&body', 'Bath&Body'), ('vegetables', 'Vegetables'), ('snacks', 'Snacks'), ('meats', 'Meats'), ('drinks', 'Drinks'), ('sweets', 'Sweets'), ('canned', 'Canned')], default='bath&body', max_length=50),
        ),
    ]
