# Generated by Django 5.2.12 on 2026-04-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('bath&body', 'Bath&Body'), ('vegetables', 'Vegetables'), ('snacks', 'Snacks'), ('meats', 'Meats'), ('drinks', 'Drinks'), ('sweets', 'Sweets'), ('canned', 'Canned'), ('seasonings', 'Seasonings'), ('laundry', 'Laundry')], default='bath&body', max_length=50),
        ),
    ]
