# Generated by Django 5.2.12 on 2026-04-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_tracking',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
